apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::820625201572:role/eksctl-eksctl-demo-nodegroup-ng-a-NodeInstanceRole-WR6LSLZ3CGV9
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::820625201572:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-04T21:56:44Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1576"
  uid: c0d27ba0-52ac-4cfa-b752-940bebbba9ad
